### PR TITLE
Normalize file paths so that tests can pass across different platforms.

### PR DESCRIPTION
**Pull request by jonkemp**
Currently, tests will fail on Windows if a forward slash is in the path if the path is a string. Likewise, if the file tree is passed in, the tests fail on Windows because the path is joined with a forward slash.

This patch normalizes the path in the assertion to make it work cross-platform.

### CODE REVIEW

**Comment by jonkemp** [comment]
Discussion?

**Comment by joakimbeng** [comment]
Sorry, had missed the notification..

Looks great, thank you! :)

**Comment by joakimbeng** [comment]
Released in version `0.1.1`

**Comment by jonkemp** [comment]
:+1:

**Pull request merged**
